### ISSUE TITLE
How do I compile it under os x?

### ISSUE THREAD

**Issue by guilhermeleobas** [w8rbt/oathgen#6]
Hi, I tried to compile the code in os x but the build.sh returns "nothing yet".

I also installed the cryptopp lib and build it with linux config.

**Comment by seansummers** [comment]
build.sh quickly exists with "nothing yet" for <system> of "mac", with no other information and the first paragraph of readme.txt states that OS X has been supported [since the first commit].

If you keep this issue Open, and wait to update your documentation so that it is correct (or reference pull request #7), those of us that want to follow your progress can use the tools that GitHub created for that.

Good luck with your project, either way!



Good luck with your project!
